== Lab 01 setup vault on OpenShift


=== Standalone Deployment

Single instance installation

```
oc new-project hashicorp

oc create -f vault-standalone/

```

The following kubernetes components will be created:

* vault-server-binding ClusterRoleBinding
* vault ServiceAccount
* vault-storage PersistentVolumeClaim with 10Gi size
* vault-config ConfigMap
* vault Serivce
* vault Deployment
* vault Route
* vault NetworkPolicy



NOTE:  vault-server-binding ClusterRoleBinding allows vault service account to leverage Kubernetes oauth with the oauth-delegator ClusterRole

////

> In case of OpenShift SDN Multitenant
>


----
oc adm  pod-network make-projects-global hashicorp
----



////


=== Initialize and unseal Vault

Initialization is the process by which Vault's storage backend is prepared to receive data. +

When a Vault server is started, it starts in a **sealed state**.
In this state, Vault is configured to know where and how to access the physical storage,
but doesn't know how to decrypt any of it. +


**Unsealing** is the process of constructing the master key necessary to read the
decryption key to decrypt the data, allowing access to the Vault.
Prior to unsealing, almost no operations are possible with Vault.



NOTE: This command below cannot be run against already-initialized Vault cluster.

```
POD=$(oc get pods -lapp.kubernetes.io/name=vault --no-headers -o custom-columns=NAME:.metadata.name)
oc rsh $POD

export VAULT_ADDR='https://localhost:8200'
export VAULT_SKIP_VERIFY="true"

vault operator init  -key-shares=1 -key-threshold=1
```

Save the `Unseal Key 1` and the `Initial Root Token`:

```
Unseal Key 1: imardDD5OHIO4hhpvruil3mSWi6CHtU7AXfjWcL+ZnI=

Initial Root Token: s.eMMrd20wonymLirGUqmHKncS

```

And export them as environment variables, for further use:

```
export VAULT_SKIP_VERIFY="true"
export KEYS=imardDD5OHIO4hhpvruil3mSWi6CHtU7AXfjWcL+ZnI=
export ROOT_TOKEN=s.eMMrd20wonymLirGUqmHKncS
export VAULT_TOKEN=$ROOT_TOKEN
```

Unseal Vault with following command:

```
vault operator unseal $KEYS

```

you should get similar to this message:

----
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.3.2
Cluster Name    vault-cluster-09f04252
Cluster ID      112fb9f3-76cd-a688-817d-06704df26bd1
HA Enabled      false

----

you should see that vault property **Sealed** is set to **false**
